# states.py
from telegram.ext import ConversationHandler

# Состояния пользователя
MAIN, ADMIN, SUPERADMIN = range(3)

# Управление прайсом
PRICE_MENU, ORDERS_MENU = range(3, 5)
ADD_PRODUCT_NAME, ADD_PRODUCT_CATEGORY, ADD_PRODUCT_PRICE, ADD_PRODUCT_STOCK, ADD_PRODUCT_PHOTO = range(5, 10)
EDIT_PRODUCT_SELECT, EDIT_PRODUCT_FIELD, EDIT_PRODUCT_VALUE = range(10, 13)
DELETE_PRODUCT_SELECT, TOGGLE_STOCK_SELECT = range(13, 15)

# Оформление заказа
ORDER_FIO, ORDER_PHONE, ORDER_PRODUCT, ORDER_QUANTITY, ORDER_ADDRESS, ORDER_COMMENT, ORDER_CONFIRM = range(15, 22)

# Управление клиентами
SEARCH_CLIENT, SEND_MESSAGE, BROADCAST_TEXT, BROADCAST_CONFIRM = range(22, 26)

# Рефералы и заказы
REFERRAL, MY_ORDERS, PERIOD_START, PERIOD_END = range(26, 30)

# Управление менеджерами и импорт
IMPORT_PRODUCTS, VIEW_MANAGERS, ADD_MANAGER_ID, REMOVE_MANAGER_ID = range(30, 34)