name: Deploy PROD

on:
  push:
    branches:
      - main

jobs:
  deploy_prod:
    runs-on: self-hosted
    env:
      COMPOSE_FILE: docker-compose.prod.yml
      ENV_FILE: .env.prod.docker

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          touch $ENV_FILE
          echo "${{ secrets.PROD_ENV }}" >> $ENV_FILE

      - name: Build containers
        run: docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" build --pull

      - name: Stop old containers
        run: docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" down --remove-orphans

      - name: Start containers
        run: docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d
