name: Deploy to Server

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create .env file from GitHub Secrets
        run: |
          mkdir -p ./telegram-shop-bot-master/telegram-shop-bot-master
          echo "${{ secrets.PROD_ENV }}" > ./telegram-shop-bot-master/telegram-shop-bot-master/.env.prod.docker

      - name: Create credentials.json from GitHub Secrets
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > ./telegram-shop-bot-master/telegram-shop-bot-master/credentials.json

      - name: Build and deploy containers
        run: |
          # Используем старую команду docker-compose (с дефисом)
          docker-compose build
          docker-compose down --remove-orphans
          docker-compose up -d